brew "gh"

cask "1password"
cask "bartender"
cask "cloudflare-warp"
cask "ghostty"
cask "google-drive"
cask "notion"
cask "notion-calendar"
cask "notion-mail"
cask "orbstack"
cask "raycast"
cask "visual-studio-code"
