tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"

brew "pinentry-mac"
brew "ykman"

cask "1password"
cask "bartender"
cask "cloudflare-warp"
cask "docker"
cask "font-jetbrains-mono"
cask "gpg-suite-no-mail"
cask "google-chrome"
cask "lens"
cask "microsoft-edge"
cask "microsoft-office"
cask "rectangle"
cask "slack"
cask "visual-studio-code"
cask "yubico-yubikey-manager"
